[package]
name = "piston-grok"
version = "0.1.0"
authors = ["arjun"]

[[bin]]
name = "piston-grok"

[dependencies]
piston = "0.32.0"
piston2d-graphics = "0.21.1"
pistoncore-glutin_window = "0.37.0"
piston2d-opengl_graphics = "0.43.0"
